#!/usr/bin/env bash
# このファイルは https://github.com/seiren-games/dev-infra で管理されています。様々なリポジトリで共有することが目的のファイルです。
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"

"$repo_root/scripts/secret-scan" pre-commit
exec "$repo_root/scripts/check-staged"
