#!/usr/bin/env bash
# このファイルは https://github.com/seiren-games/dev-infra で管理されています。様々なリポジトリで共有することが目的のファイルです。
set -euo pipefail

remote_name="${1:-}"

exec "$(git rev-parse --show-toplevel)/scripts/secret-scan" pre-push "$remote_name"
