# このファイルは https://github.com/seiren-games/dev-infra で管理されています。様々なリポジトリで共有することが目的のファイルです。

[target.x86_64-pc-windows-gnu]
image = "ghcr.io/cross-rs/x86_64-pc-windows-gnu@sha256:c58423353aecebe5e9ebafb97873afc9264dbfa0d8c1875fc3b66282d73f5eda"
